### ISSUE TITLE
Why `Blake-256 String` is different from other tools?

### ISSUE THREAD

**Issue by kaigedong** [shawntabrizi/substrate-rpc-examples#1]
I am using `Blake-256 a String` Function in https://www.shawntabrizi.com/substrate-rpc-examples/utils/.

For a string like `0x01000000`, it will generate `0xe12c22d4f162d9a012c9319233da5d3e923cc5e1029b8f90e47249c9ab256b35 `.

But using other `BLAKE2b-256` implement ( [https://toolkitbay.com/tool/BLAKE2b_256](https://toolkitbay.com/tool/BLAKE2b_256) ) it will generate  `91e1f12bcd6937f6c389a2248141063c02bf9c6083fee9c9776492304afc9a28`, Same as other implement.

So what happened when generate a `Blake-256 String` in the web?

**Comment by kaigedong** [comment]
Is it because the difference of `Blake` and `Blake2`? 

I didn't find a tool to generate a Blake hash, most of which only offer Blake2 hash algorithm.

**Comment by kaigedong** [comment]
> Is it because the difference of `Blake` and `Blake2`?
> 
> I didn't find a tool to generate a Blake hash, most of which only offer Blake2 hash algorithm.

I am wrong!  I am trying to read the js code. It would better if you could offer a  brief clarify.

**Comment by kaigedong** [comment]
I figure out this problem.

**Comment by shawntabrizi** [comment]
What was the issue?

Was it that you used the string "0x01000000" when you mean to pass some encoded bytes instead?
