### ISSUE TITLE
metadata decoder

### ISSUE THREAD

**Issue by roccomuso** [shawntabrizi/substrate-rpc-examples#2]
Can you tell how the metadata is encoded? and how to parse it using JS?

Also, is there a way to create an unsigned polkadot tx without having to rely on this huge metadata data?

**Comment by shawntabrizi** [comment]
No, you need to use the metadata. If you hardcode some representation of the metadata, you risk having that information go out of date when Polkadot pushes a breaking change through an upgrade.

The Metadata is SCALE encoded: https://substrate.dev/docs/en/knowledgebase/advanced/codec

The base encoding of the metadata can be found here: https://github.com/paritytech/substrate/blob/master/frame/metadata/src/lib.rs
